### ISSUE TITLE
As a teacher I when I check the Merge Checked Views button the colors of the points should not be be reassigned when the student update the points so that the changes are not confusing.

### ISSUE THREAD

**Issue by cfblack** [MathNetDev/MathNetClient#10]

**Comment by IsaacNPsmash** [comment]
Test Dev 9/14/18 @ 9:38 CST
This color reassigning when students update the points seems to be fixed for Dev-Filtered merge view, i.e. when the teacher has merged views, live is on, and a student moves a point, the color of the points, line, and conic do not change. When the teacher hasn't merged view yet, so they can see all groups, and a student moves a point, that line in that graph changes back to default blue, but this doesn't seem like a problem.
This is not an issue in "View" because it is not live or in "Overlay image view" because it does not assign colors.

**Comment by cbradyatinquire** [comment]
colors are working as desired (modulo the other open issue on first time merge).
