### ISSUE TITLE
Send the perspectives+tools from the Activity Designer

### ISSUE THREAD

**Issue by cbradyatinquire** [MathNetDev/MathNetClient#19]
As much as possible, the perspectives and tools from Activity Designer should be sent to the students

**Comment by mtstevens** [comment]
Tested within MathNetTest, 07/20/18 @ 9:25am. Toolbars (identical and differentiated) were successfully sent to students. Perspectives (identical and differentiated) were successfully sent to students; however, there were some issues with Manual Perspectives:

1) "Graphics" sent to "mike1" and "Graphics 2" sent to "mike2". Axes scales and toolbars were not identical. Within User Customizations, window dimensions were blank and "use above settings for Graphics 2" was checked.
![screen shot 2018-07-20 at 9 29 08 am](https://user-images.githubusercontent.com/41483974/43014107-f5b9ae36-8bff-11e8-864e-4cd7a0243ee1.png)

2) Following #1 above, Window Dimensions set to Ymax=10, Xmin=-10, Xmax=10, Ymin=-10. X and Y Axis Steps both set to 1. Numerical scaling was successful; however, the axes in "Graphics" (on mike1's screen) don't appear to be in scale.
![screen shot 2018-07-20 at 9 38 12 am](https://user-images.githubusercontent.com/41483974/43014326-a8779b50-8c00-11e8-8abb-96ae98da0f6e.png)

**Comment by mtstevens** [comment]
Tested in both Test and Dev, 08/23/18 @ 4:40pm PDT. Different sets of perspectives were sent to students, with mixed results. The sets tested and their outcomes are listed below:

Graphics 1 with Graphics 2 (successful test)
Algebra with Graphics 1 and 2 (successful test)
Graphics 1 with Spreadsheet (successful test)
Algebra with Graphics 1 and Spreadsheet (successful test)
Graphics 1 with 3D Graphics (TEST FAILED)
3D Graphics Only (TEST FAILED)

For both of the failed 3D Graphics tests above, the students received the "default" perspectives of Algebra with Graphics 1.

As expected, the default toolsets for each of the selected perspectives were successfully sent to the students. Different/differentiated toolsets were not tested because these would have come from User Customizations and would override any selected perspectives from the Activity Designer.

**Comment by cbradyatinquire** [comment]
To discuss in next meeting  - What do we need for 3D Graphics as a perspective

**Comment by cbradyatinquire** [comment]
closed modulo the zoom settings (another issue for this)
